package org.renci.canvas.dao;

import java.io.File;
import java.util.EnumSet;

import org.hibernate.boot.MetadataSources;
import org.hibernate.boot.registry.StandardServiceRegistryBuilder;
import org.hibernate.tool.hbm2ddl.SchemaExport;
import org.hibernate.tool.schema.TargetType;
import org.junit.Test;

public class TestSchemaExport {

    @Test
    public void test() {

        MetadataSources metadata = new MetadataSources(
                new StandardServiceRegistryBuilder().applySetting("hibernate.dialect", "org.hibernate.dialect.PostgreSQLDialect").build());

        // grabbed from the persistence.xml file
        metadata.addAnnotatedClass(org.renci.canvas.dao.annotation.model.AnnotationCodingSequence.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.annotation.model.AnnotationCodingSequenceExternalId.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.annotation.model.AnnotationCodingSequenceExternalIdPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.annotation.model.AnnotationGene.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.annotation.model.AnnotationGeneExternalId.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.annotation.model.AnnotationGeneExternalIdPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.annotation.model.AnnotationGeneSynonym.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.annotation.model.AnnotationGeneSynonymPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.annotation.model.AnnotationTranscriptionMapWarnings.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.AnalysisClass.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.AnalysisClassIncidental.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.AnalysisNote.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.BinGeneSymbol.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.BinGeneSymbolPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.BinResultsFinalDiagnostic.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.BinResultsFinalDiagnosticPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.BinResultsFinalIncidental.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.BinResultsFinalIncidentalPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.BinResultsFinalIncidentalX.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.BinResultsFinalIncidentalXPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.BinResultsFinalRiskX.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.BinResultsFinalRiskXPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.BinningJob.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.CarrierStatus.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.ClinBinStatusType.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.ConfirmedTracking.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.DX.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.DXCoverage.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.DXCoveragePK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.DXExons.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.DiagnosticBinResults.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.DiagnosticBinResultsPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.DiagnosticBinningJob.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.DiagnosticGene.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.DiagnosticGeneGroupVersion.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.DiagnosticGeneGroupVersionPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.DiagnosticResultVersion.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.DiagnosticStatusType.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.DiseaseClass.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.HaplotypeX.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.IncidentalBin.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.IncidentalBinGene.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.IncidentalBinGenePK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.IncidentalBinGeneX.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.IncidentalBinGeneXPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.IncidentalBinGroupVersion.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.IncidentalBinGroupVersionPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.IncidentalBinGroupVersionX.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.IncidentalBinGroupVersionXPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.IncidentalBinHaplotypeX.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.IncidentalBinHaplotypeXPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.IncidentalBinResults.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.IncidentalBinResultsPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.IncidentalBinType.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.IncidentalBinX.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.IncidentalBinningJob.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.IncidentalResultVersion.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.IncidentalResultVersionX.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.IncidentalStatusType.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.MaxFrequency.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.MaxFrequencyPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.MaxFrequencySource.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.MissingHaplotype.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.MissingHaplotypePK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.NCGenesFrequencies.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.NCGenesFrequenciesPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.PhenotypeX.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.Report.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.ReportPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.RsVariants.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.RsVariantsPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.UnimportantExon.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.UnimportantExonPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.UnimportantFeature.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.UnimportantFeaturePK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinbin.model.ZygosityModeType.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinvar.model.AssertionRanking.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinvar.model.ReferenceClinicalAssertion.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinvar.model.SubmissionClinicalAssertion.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinvar.model.TraitSet.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinvar.model.Trait.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.clinvar.model.ClinVarVersion.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.dbsnp.model.MappingWarning.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.dbsnp.model.RSMappingT.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.dbsnp.model.RSMappingTPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.dbsnp.model.SNP.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.dbsnp.model.SNPAllele.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.dbsnp.model.SNPAlleleFrequency.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.dbsnp.model.SNPAlleleFrequencyPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.dbsnp.model.SNPAllelePK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.dbsnp.model.SNPGenotypeFrequency.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.dbsnp.model.SNPGenotypeFrequencyPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.dbsnp.model.SNPHWProb.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.dbsnp.model.SNPHWProbPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.dbsnp.model.SNPMapping.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.dbsnp.model.SNPMappingAgg.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.dbsnp.model.SNPMappingAggPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.dbsnp.model.SNPMappingPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.dbsnp.model.SNPMappingWarning.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.dbsnp.model.SNPMappingWarningPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.esp.model.ESPSNPFrequencyPopulation.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.esp.model.ESPSNPFrequencyPopulationPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.exac.model.ExACMaxVariantFrequency.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.exac.model.ExACMaxVariantFrequencyPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.exac.model.ExACVariantFrequency.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.exac.model.ExACVariantFrequencyPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.gnomad.model.GnomADMaxVariantFrequency.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.gnomad.model.GnomADMaxVariantFrequencyPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.gnomad.model.GnomADVariantFrequency.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.gnomad.model.GnomADVariantFrequencyPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.onekgen.model.OneKGenomesIndelMaxFrequency.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.onekgen.model.OneKGenomesIndelMaxFrequencyPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.onekgen.model.OneKGenomesIndelFrequency.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.onekgen.model.OneKGenomesIndelFrequencyPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.onekgen.model.OneKGenomesSNPFrequencyPopulation.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.onekgen.model.OneKGenomesSNPFrequencyPopulationPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.onekgen.model.OneKGenomesSNPFrequencySubpopulation.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.onekgen.model.OneKGenomesSNPFrequencySubpopulationPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.onekgen.model.OneKGenomesSNPPopulationMaxFrequency.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.onekgen.model.OneKGenomesSNPPopulationMaxFrequencyPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.hgmd.model.HGMDLocatedVariant.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.hgmd.model.HGMDLocatedVariantPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.hgnc.model.HGNCGene.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.hgnc.model.HGNCStatusType.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.hgnc.model.LocusGroup.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.hgnc.model.LocusType.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.omim.model.OMIMGene.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.omim.model.Otype.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.omim.model.Phenotype.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.ref.model.GenomeRef.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.ref.model.GenomeRefSeq.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.ref.model.GenomeRefSeqAlternateId.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.ref.model.GenomeRefSeqAlternateIdPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.ref.model.GenomeRefSeqLocation.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.ref.model.GenomeRefSeqLocationPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.ref.model.SequenceType.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.refseq.model.CDSECNumber.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.refseq.model.CDSECNumberPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.refseq.model.CDSTranslationException.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.refseq.model.CDSTranslationExceptionPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.refseq.model.Feature.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.refseq.model.FeatureType.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.refseq.model.FeatureQualifiers.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.refseq.model.FeatureQualifiersPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.refseq.model.GroupingType.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.refseq.model.LocationType.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.refseq.model.RefSeqCodingSequence.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.refseq.model.RefSeqGene.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.refseq.model.RegionGroup.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.refseq.model.RegionGroupRegion.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.refseq.model.RegionGroupRegionPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.refseq.model.Transcript.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.refseq.model.TranscriptMaps.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.refseq.model.TranscriptMapsExons.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.refseq.model.TranscriptMapsExonsPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.refseq.model.TranscriptMapsWarnings.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.refseq.model.TranscriptMapsWarningsPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.refseq.model.TranscriptRefSeqVersion.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.refseq.model.TranscriptRefSeqVersionPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.refseq.model.VariantEffect.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.refseq.model.Variants_48_2.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.refseq.model.Variants_48_2PK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.refseq.model.Variants_61_2.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.refseq.model.Variants_61_2PK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.refseq.model.Variants_80_4.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.refseq.model.Variants_80_4PK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.var.model.Assembly.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.var.model.AssemblyLocatedVariant.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.var.model.AssemblyLocatedVariantPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.var.model.AssemblyLocatedVariantQC.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.var.model.AssemblyLocatedVariantQCPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.var.model.AssemblyLocation.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.var.model.AssemblyLocationPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.var.model.CanonicalAllele.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.var.model.Lab.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.var.model.Library.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.var.model.LocatedVariant.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.var.model.Project.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.var.model.Sample.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.var.model.VariantSet.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.var.model.VariantSetLoad.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.var.model.VariantSetLocation.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.var.model.VariantSetLocationPK.class);
        metadata.addAnnotatedClass(org.renci.canvas.dao.var.model.VariantType.class);

        File output = new File("target", "database.sql");
        if (output.exists()) {
            output.delete();
        }
        new SchemaExport().setDelimiter(";").setOutputFile(output.getAbsolutePath()).createOnly(EnumSet.of(TargetType.SCRIPT),
                metadata.buildMetadata());

    }

}
