CREATE TABLE annot.annotation_versions (annotation_module varchar(500) NOT NULL, annotation_version varchar(100) NOT NULL, ref_id integer NOT NULL, FOREIGN KEY(ref_id) REFERENCES ref.genome_ref(ref_id));
INSERT INTO annot.annotation_versions VALUES ('ClinVar','1',2);
INSERT INTO annot.annotation_versions VALUES ('ClinVar','4',2);
INSERT INTO annot.annotation_versions VALUES ('ClinVar','5',2);
INSERT INTO annot.annotation_versions VALUES ('dbSNP','134',2);
INSERT INTO annot.annotation_versions VALUES ('dbSNP','137',2);
INSERT INTO annot.annotation_versions VALUES ('ESP','1',2);
INSERT INTO annot.annotation_versions VALUES ('EXaC','0.1',2);
INSERT INTO annot.annotation_versions VALUES ('1kg_indesfreq','1',2);
INSERT INTO annot.annotation_versions VALUES ('1kg_snpfreq','1',2);
INSERT INTO annot.annotation_versions VALUES ('NCGenesFrequencies','80',2);
INSERT INTO annot.annotation_versions VALUES ('NCGenesFrequencies','133',2);
INSERT INTO annot.annotation_versions VALUES ('NCGenesFrequencies','602',2);
INSERT INTO annot.annotation_versions VALUES ('HGMD','2',2);
INSERT INTO annot.annotation_versions VALUES ('RefSeq','48',2);
INSERT INTO annot.annotation_versions VALUES ('RefSeq','61',2);
INSERT INTO annot.annotation_versions VALUES ('RefSeq','80',4);
